<?PHP
/*
    Nombre: instalado.inc
    Autor: Julio Tuozzo
    Función: mensaje una vez completada la instalación de PHD Help Desk
    Ver: 2.12
*/

echo "<h1>PHD Help Desk 2.12 ya se encuentra instalado!!</h1>

<h2><a href='http://www.p-hd.com.ar/registro.php'>T&oacute;mese unos minutos para registrarse en <b>PHD Help Desk</b></a></h2>

<p class='danger'><small><b>IMPORTANTE:</b> Una vez instalado <b>PHD Help Desk</b> se recomienda mover a un lugar seguro y fuera del alcance de los usuarios estos programas de instalaci&oacute;n que se encuentran en <b>/phd_2_12/setup/</b>.</small></p>

<h4>Si desea solicitar soporte o realizar consultas sobre funcionalidades ingrese a nuestro foro
en <a href='http://www.p-hd.com.ar/foro.php' >http://www.p-hd.com.ar/foro.php</a>
</h4>
<br />

</body>
</html>";

?>
