<?PHP
/*
    Nombre: head_frame.inc
    Autor: Julio Tuozzo
    Función: HEAD de las páginas con iframe
    Function: Iframe page's Head.
    Ver: 1.43
*/
echo
"<!doctype html public '-//W3C//DTD HTML 4.01 Frameset//EN'>
<html>

<head>
  <meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>
  <title>PHD Help Desk &nbsp; ($_SESSION[PHD_OPERADOR]) - $_SESSION[PHD_APE_Y_NOM] / $_SESSION[PHD_SECTOR_ID] </title>
  <link href='phd.css' rel='stylesheet' type='text/css' />
  <link rel='shortcut icon' href='favicon.ico' type='image/x-icon' />
</head> \n";

?>
