<?PHP
/*
    Nombre: head.inc
    Autor: Julio Tuozzo
    Función: HEAD de las páginas
    Function: Page's Head.
    Ver: 1.43

*/

echo
"<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en' lang='en'>
<head>
  <meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>
  <title>PHD Help Desk &nbsp; ($_SESSION[PHD_OPERADOR]) - $_SESSION[PHD_APE_Y_NOM] / $_SESSION[PHD_SECTOR_ID] </title>
  <LINK REL=STYLESHEET TYPE='text/css' HREF='phd.css' TITLE='estilo'>
  <link rel='shortcut icon' href='favicon.ico' />
  $frames
</head> \n";

?>
