<?PHP
/*
    Nombre: instalado.inc
    Autor: Julio Tuozzo
    Función: Install complete message
    Ver: 2.12
*/

echo "<h1>PHD Help Desk 2.12 is already installed!!!</h1>

<h2><a href='http://www.p-hd.com.ar/eng/registro.php'>Take a few minutes to registry in <b>PHD Help Desk</b></a></h2>



<p class='danger'><small><b>IMPORTANT:</b> Once installed <b>PHD Help Desk</b> we recommend to move to a safe place and outside the scope of the users these install programs that are in <b>/phd_2_12/setup/</b>.</small></p>

<h4>If you need to ask for support or do consultations on functionalities visit our forum at
<a href='http://www.p-hd.com.ar/eng/foro.php' >http://www.p-hd.com.ar/eng/foro.php</a>
</h4>
<br />

</body>
</html>";

?>
