<?PHP
/*
    Name: setup_head.inc
    Autor: Julio Tuozzo
    Función: Pages Head
    Ver: 2.12
*/

echo
"
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN'
    'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='es' lang='es'>

<head>
  <meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1' />
  <title>PHD Help Desk 2.12 initial configuration</title>
  <link rel='stylesheet' type='text/css' href='phd.css' />
  <link rel='shortcut icon' href='favicon.ico' />
</head>

<body>

<div class='encabezado'>
        <a href='http://www.p-hd.com.ar'><img src='phd_400_55.gif' border='0' alt='PHD Help Desk' /></a>
</div>

<div class='menu'>
<table border='0' width='100%' cellpadding='1' cellspacing='1'>
  <tr>
    <td>   <a href='http://www.p-hd.com.ar/eng/'>PHD Help Desk home page</a>
    </td>
    <td> <a href='http://www.p-hd.com.ar/eng/registro.php'>Registry in PHD Help Desk</a>
    </td>
    <td> <a href='http://www.p-hd.com.ar/eng/user_guide_2_12.php'>Download the user guide of PHD Help Desk</a>
    </td>
  </tr>
 </table>
</div>

<h2>PHD Help Desk 2.12 configuration.</h2>";
?>
